[package]
name = "namespace"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

edition = "2018"

[dependencies]
netlink = { path = "../netlink" }

anyhow = "1"
exec = "0.3"
libc = "0.2"
nix = "0.10"
rand = "0.7"
