[package]
name = "tool"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]
fdns-parse = { path = "../../fdns/parse" }
namespace = { path = "../namespace" }

byteorder = "1"
cast = "0.2"
error-chain = "0.11"
hex = "0.3"
itertools = "0.7"
mio = "0.6"
# until https://github.com/courvoif/pcap-file/pull/4 is merged
pcap-file = { git = "https://github.com/FauxFaux/pcap-file", branch = "error-11" }
